### ISSUE TITLE
Cannot monitor file or directory creation in Explorer

### ISSUE THREAD

**Issue by leochou0729** [tresorit/rdcfswatcherexample#3]
Hello,
When I create a new file or directory in Explorer, the watcher program only prints this line:
Change on watcher with ID=1, relative path: "
Then the whole program cannot monitor any more.

Thanks!

**Comment by kovbal** [comment]
Hello!
Thank you for reporting this issue!
I was able to reproduce it with filenames that contained non-ASCII characters, like emojis. I created PR  #4 that fixed the issue in my environment. Can you check my solution, and comment on the PR?
Thanks!
